// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function getDatabaseUrl() {
  const databaseUrl = process.env["DATABASE_URL"];

  if (!databaseUrl) {
    return databaseUrl;
  }

  const url = new URL(databaseUrl);

  if (url.username === "postgress") {
    url.username = "postgres";
  }

  return url.toString();
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
