ALTER TABLE "products"
ADD COLUMN "image" TEXT,
ADD COLUMN "rating_stars" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "rating_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "keywords" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
